name: Deploy Portfolio

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t hammadrazzaq2k/my-portfolio:latest .

    - name: Push to Docker Hub
      run: docker push hammadrazzaq2k/my-portfolio:latest

    - name: Deploy to AWS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          sudo docker pull hammadrazzaq2k/my-portfolio:latest
          sudo docker stop portfolio || true
          sudo docker rm portfolio || true
          sudo docker run -d -p 80:80 --name portfolio hammadrazzaq2k/my-portfolio:latest
